### ISSUE TITLE
error when enable "use nodes"

### ISSUE THREAD

**Issue by ywaby** [Griperis/BlenderDataVis#36]
error when enable "use nodes"

```
Traceback (most recent call last):
  File "/home/ywaby/.config/blender/2.83/scripts/addons/data_vis/operators/bar_chart.py", line 116, in execute
    color_gen = color_factory.create(self.axis_settings.z_range, 2.0, self.container_object.location[2])
  File "/home/ywaby/.config/blender/2.83/scripts/addons/data_vis/colors.py", line 239, in create
    return NodeShader(self.container_name, self.base_color, self.color_type, scale, location_z)
  File "/home/ywaby/.config/blender/2.83/scripts/addons/data_vis/colors.py", line 42, in __init__
    self.material = self.create_gradient_shader()
  File "/home/ywaby/.config/blender/2.83/scripts/addons/data_vis/colors.py", line 122, in create_gradient_shader
    sub_node = self.__create_z_sub_node(nodes, material, -700)
  File "/home/ywaby/.config/blender/2.83/scripts/addons/data_vis/colors.py", line 185, in __create_z_sub_node
    drv = material.node_tree.driver_add('nodes["Math"].inputs[1].default_value')
TypeError: bpy_struct.driver_add(): property "nodes["Math"].inputs[1].default_value" not found

location: <unknown location>:-1
```

**Comment by ywaby** [comment]
ok,it fixed.
